"""Primeira tabela do banco de dados SQL

Revision ID: 01db656e774e
Revises: 
Create Date: 2026-03-19 19:53:20.133706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01db656e774e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treinador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_treinador', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treinador_id'), 'treinador', ['id'], unique=False)
    op.create_index(op.f('ix_treinador_nome_treinador'), 'treinador', ['nome_treinador'], unique=True)
    op.create_table('atleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_atleta', sa.String(), nullable=False),
    sa.Column('rank_atual', sa.String(), nullable=False),
    sa.Column('status_velocidade', sa.Float(), nullable=False),
    sa.Column('status_stamina', sa.Integer(), nullable=False),
    sa.Column('id_treinador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_treinador'], ['treinador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atleta_id'), 'atleta', ['id'], unique=False)
    op.create_index(op.f('ix_atleta_nome_atleta'), 'atleta', ['nome_atleta'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atleta_nome_atleta'), table_name='atleta')
    op.drop_index(op.f('ix_atleta_id'), table_name='atleta')
    op.drop_table('atleta')
    op.drop_index(op.f('ix_treinador_nome_treinador'), table_name='treinador')
    op.drop_index(op.f('ix_treinador_id'), table_name='treinador')
    op.drop_table('treinador')
    # ### end Alembic commands ###
