"""Atualizacao do banco de dados

Revision ID: 97a3433d1a0b
Revises: 01db656e774e
Create Date: 2026-03-22 21:36:22.003004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a3433d1a0b'
down_revision: Union[str, Sequence[str], None] = '01db656e774e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atleta_nome_atleta'), table_name='atleta')
    op.create_index(op.f('ix_atleta_nome_atleta'), 'atleta', ['nome_atleta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atleta_nome_atleta'), table_name='atleta')
    op.create_index(op.f('ix_atleta_nome_atleta'), 'atleta', ['nome_atleta'], unique=1)
    # ### end Alembic commands ###
