"""Cria a tabela com adm's

Revision ID: 63798798ee00
Revises: 
Create Date: 2026-03-16 20:58:48.467107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63798798ee00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adms_id'), 'adms', ['id'], unique=False)
    op.create_table('mercenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('arma', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mercenarios_id'), 'mercenarios', ['id'], unique=False)
    op.create_index(op.f('ix_mercenarios_nome'), 'mercenarios', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mercenarios_nome'), table_name='mercenarios')
    op.drop_index(op.f('ix_mercenarios_id'), table_name='mercenarios')
    op.drop_table('mercenarios')
    op.drop_index(op.f('ix_adms_id'), table_name='adms')
    op.drop_table('adms')
    # ### end Alembic commands ###
