"""Criacao do primeiro banco de dados

Revision ID: beb4238b75a8
Revises:
Create Date: 2026-03-18 16:13:27.168436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "beb4238b75a8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "produtor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("senha", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_produtor_id"), "produtor", ["id"], unique=False)
    op.create_table(
        "presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome_musica", sa.String(), nullable=False),
        sa.Column("software_usado", sa.String(), nullable=False),
        sa.Column("nivel_ganho", sa.Float(), nullable=False),
        sa.Column("distorcao", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["produtor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_presets_id"), "presets", ["id"], unique=False)
    op.create_index(
        op.f("ix_presets_nome_musica"), "presets", ["nome_musica"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_presets_nome_musica"), table_name="presets")
    op.drop_index(op.f("ix_presets_id"), table_name="presets")
    op.drop_table("presets")
    op.drop_index(op.f("ix_produtor_id"), table_name="produtor")
    op.drop_table("produtor")
    # ### end Alembic commands ###
