"""Adicao da data de publicacao

Revision ID: 52b564cf3989
Revises: e4e6e7c784f3
Create Date: 2026-03-13 18:53:46.283273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b564cf3989'
down_revision: Union[str, Sequence[str], None] = 'e4e6e7c784f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('ano_publicacao', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'ano_publicacao')
    # ### end Alembic commands ###
